### ISSUE TITLE
Test Bugs

### ISSUE THREAD

**Issue by bojianwangny** [gcivil-nyu-org/S2022-Team-2-repo#120]
1. In chat page, the friend profile image doesn't show correctly.
2. The chat button on My Friend page doesn't work
3. When searching for any String combined with 'u', 's', 'e', 'r', it will return a ValueError.

**Comment by manektamanna** [comment]
We are still working on the 1st and 2nd point. Its mentioned in the testing document. These are the things that does not work as of now.

The search functionality is not working because somebody unknowingly broke our user profile.He tried to test functionality that was not to be tested which basically broke the user profiles
