### ISSUE TITLE
Testing Party bugs

### ISSUE THREAD

**Issue by RIC06X** [gcivil-nyu-org/S2022-Team-2-repo#127]
1. Click My friends on the nav bar shows Value Error (when the user has no friends?)
<img width="1589" alt="Screen%20Shot%202022-04-17%20at%2016 27 11" src="https://user-images.githubusercontent.com/18493288/163731988-ac151f3c-b80b-48e2-926a-f3455b674130.png">

2. Can upload any size of photo (100M, 500M) in update profile page3. 

3. Clear check-box is causing ValueError when checked and click submit button (possibly large size photo is causing this problem)

4. Chat function not working, cannot click chat button in dashboard/my_friends

**Comment by manektamanna** [comment]
The value error is coming because you tried to clear the check box on the profile update page. That is yet to be figured out. It is written in the document that clear checkbox should not be tested. Because few people tested it, the user profile got broke and thats is why you are receiving Value errors everywhere. About the chat functionality, that is also specified in the document that chats won't work for specific friends if you want to directly chat with them by clicking the chat button. On the sidebar, you will see the Chat option where you can add friends from the top right corner and chat with them.
