### ISSUE TITLE
Testing Party 

### ISSUE THREAD

**Issue by srijanmalhotra2711** [gcivil-nyu-org/S2022-Team-2-repo#130]
1. **Not interested** should automatically go if others checked, Should be redirected to the preferences page instead of the index page.

2. Typed User One, did not give output and the **code malfunctioned**.

![Screen Shot 2022-04-17 at 20.01.02.png](https://images.zenhubusercontent.com/62052e0dcd174000595a4a54/40fab496-eed3-49a2-903c-3bfae508b35d)

3. Clicking on the chat option on the My Friends page doesn't take me to the chat option.
4. Chat option on the My Friend page doesn't work. 
5. Clicking My Friend's options gives me an error. 

![Screen Shot 2022-04-17 at 20.10.17.png](https://images.zenhubusercontent.com/62052e0dcd174000595a4a54/5939656f-7236-4435-96ba-f2a19a9f535c)

**Comment by manektamanna** [comment]
It's written in the document that the chat button on the My Friends page won't work for now. The value error that you are getting on all pages is because you might have tried to use the clear checkbox while updating your profile. which was not to be tested (also specified in the document).

The first point that you mentioned is not clear to me. Can you please elaborate? I think that is how it is supposed to work.
